AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Table mínima para pruebas"

Parameters:
  TableName:
    Type: String
    Default: books-acoplada
    Description: DynamoDB table Name

Resources:
  booksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: book_id
          AttributeType: S
      KeySchema:
        - AttributeName: book_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref booksTable

  TableArn:
    Description: ARN DynamoDB table
    Value: !GetAtt booksTable.Arn
